packaging_format = 2

id = "grocy"
name = "Grocy"
description.en = "Web-based groceries & household management solution for your home"
description.fr = "Solution Web de gestion d'épicerie et de gestion de la maison"

version = "4.0.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://grocy.info/"
demo = "https://en.demo.grocy.info/stockoverview"
code = "https://github.com/grocy/grocy"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap =  true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"
[install]
    [install.domain]
    type = "domain"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["de", "en", "es", "fr", "it", "pt"]
    default = "fr"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/grocy/grocy/releases/download/v4.0.2/grocy_4.0.2.zip"
        sha256 = "6615df64a99f83c952cc4006223ecb3087ef6871b5158e63fbf3a93824f19b77"
        in_subdir = false
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "grocy_.*.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "php8.2-ldap php8.2-mbstring php8.2-fileinfo php8.2-sqlite3 php8.2-gd php8.2-intl"
